homepage_route: "home"
profile: "/profile\\/[a-zA-Z]+/"
routes:
    home:       "Main:home"
    register:   "Main:register"
    login:      "Main:login"
    logout:     "Main:logout"
    profile:    "Main:profile" 
